language: c
dist: trusty
compiler:
  - clang
  - gcc
before_install:
  - sudo add-apt-repository ppa:ondrej/apache2 -y
  - sudo apt-get -qq update
  - sudo apt-get install -y libev-dev libuv1-dev
install: ./autogen.sh
script:
  - ./configure
  - make dist
  - tar zxvf *.tar.gz
  - cd dumdumd-*[0-9]
  - mkdir build
  - cd build
  - ../configure
  - make
  - src/dumdumd -h
