dist: xenial
addons:
  apt:
    update: true
    packages:
    - libev-dev
    - libuv1-dev
language: c
compiler:
  - clang
  - gcc
install: ./autogen.sh
script:
  - ./configure
  - make dist
  - tar zxvf *.tar.gz
  - cd dumdumd-*[0-9]
  - mkdir build
  - cd build
  - ../configure
  - make
  - src/dumdumd -h
