name: C/C++ CI

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: configure
      run: sh autogen.sh && mkdir -p build && cd build && ../configure --enable-warn-all
    - name: make
      run: make clean all test
